language: node_js
node_js: stable

# S: Build Lifecycle
install:
  - npm install
  - git clone https://github.com/theme-next/hexo-theme-next themes/next
  
script:
  - sed -i "608,609d" themes/next/_config.yml
  - sed -i "/disqus:/a \ \ shortname: haoyu-blog" themes/next/_config.yml
  - sed -i "/disqus:/a \ \ enabled: true" themes/next/_config.yml
  - hexo g

after_script:
  - cd ./public
  - git init
  - git add .
  - git commit -m "Update docs"
  - git remote add azure https://${AZURE_WA_USERNAME}:${AZURE_WA_PASSWORD}@${AZURE_WA_SITE}
  - git push azure master --force
